server:
  http-port: ${FF_PORT:18880}
  http2:
    enabled: ${FF_HTTPS:true}
  ssl:
    enabled: ${FF_HTTPS:true}
    port: ${FF_HTTPS_PORT:18881}
    forced: ${FF_HTTPS_FORCED:true}
    key-store: ${FF_HTTPS_CERT:classpath:config/cert.pfx}
    key-store-password: ${FF_HTTPS_CERT_PASSWORD:12345678}
  servlet:
    session:
      timeout: ${FF_SESSION_TIMEOUT:60s}
logging:
  level:
    com.github.filefusion: ${FF_LOG_LEVEL:INFO}
  file:
    name: ${FF_LOG_DIR:/opt/file_fusion/logs}/log.log
spring:
  redis:
    redisson:
      file: ${FF_REDIS_CONFIG_FILE:classpath:config/redisson.yml}
  datasource:
    driver-class-name: ${FF_DATASOURCE_DRIVER:org.h2.Driver}
    url: ${FF_DATASOURCE_URL:jdbc:h2:file:/opt/file_fusion/data/db/database;DATABASE_TO_UPPER=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE}
    username: ${FF_DATASOURCE_USERNAME:file_fusion}
    password: ${FF_DATASOURCE_PASSWORD:file_fusion}
security:
  secret:
    public-key: ${FF_SECRET_PUBLIC_KEY:/opt/file_fusion/secret/id_ed25519.pub}
    private-key: ${FF_SECRET_PRIVATE_KEY:/opt/file_fusion/secret/id_ed25519}
task:
  lock-timeout: ${FF_TASK_LOCK_TIMEOUT:60s}
  clear-thumbnail-file: ${FF_TASK_CLEAR_THUMBNAIL_FILE:0 0 1 * * ?}
file:
  lock-timeout: ${FF_FILE_LOCK_TIMEOUT:60s}
  download-link-timeout: ${FF_FILE_DOWNLOAD_LINK_TIMEOUT:60s}
  thumbnail-generate-timeout: ${FF_FILE_THUMBNAIL_GENERATE_TIMEOUT:60s}
  dir: ${FF_FILE_DIR:/opt/file_fusion/data/file}
  tmp-dir: ${FF_FILE_TMP_DIR:/opt/file_fusion/data/tmp}
  recycle-bin-dir: ${FF_FILE_RECYCLE_BIN_DIR:/opt/file_fusion/data/recycle_bin}
  thumbnail-dir: ${FF_FILE_THUMBNAIL_DIR:/opt/file_fusion/data/thumbnail}
  thumbnail-image-mime-type: "${FF_FILE_THUMBNAIL_IMAGE_MIME_TYPE:application/pdf,\
    application/postscript,\
    image/bmp,\
    image/gif,\
    image/heic,\
    image/jpeg,\
    image/png,\
    image/sgi,\
    image/svg+xml,\
    image/tiff,\
    image/vnd.adobe.photoshop,\
    image/webp,\
    image/x-xbitmap}"
  thumbnail-video-mime-type: "${FF_FILE_THUMBNAIL_VIDEO_MIME_TYPE:application/vnd.rn-realmedia,\
    video/x-ms-wmv,\
    video/mp4,\
    video/mpeg,\
    video/3gpp,\
    video/x-flv,\
    video/quicktime,\
    video/mp4,\
    video/x-flv,\
    video/webm,\
    video/avi}"
