server:
  http-port: ${FF_PORT:18880}
  http2:
    enabled: ${FF_HTTPS:true}
  ssl:
    enabled: ${FF_HTTPS:true}
    port: ${FF_HTTPS_PORT:18881}
    forced: ${FF_HTTPS_FORCED:true}
    key-store: ${FF_HTTPS_CERT:classpath:config/cert.pfx}
    key-store-password: ${FF_HTTPS_CERT_PASSWORD:123456}
  servlet:
    session:
      timeout: ${FF_TIMEOUT:60s}
logging:
  level:
    com.github.filefusion: ${FF_LOG_LEVEL:INFO}
  file:
    name: ${FF_LOG_DIR:/opt/file_fusion/logs}/log.log
spring:
  servlet:
    multipart:
      max-file-size: ${FF_MAX_FILE_SIZE:4096MB}
      max-request-size: ${FF_MAX_REQUEST_SIZE:4096MB}
  data:
    redis:
      database: ${FF_REDIS_DATABASE:0}
      host: ${FF_REDIS_HOST:localhost}
      port: ${FF_REDIS_PORT:6379}
      password: ${FF_REDIS_PASSWORD:redis}
  datasource:
    driver-class-name: ${FF_DATASOURCE_DRIVER:org.h2.Driver}
    url: ${FF_DATASOURCE_URL:jdbc:h2:file:/opt/file_fusion/data/db/database;DATABASE_TO_UPPER=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE}
    username: ${FF_DATASOURCE_USERNAME:file_fusion}
    password: ${FF_DATASOURCE_PASSWORD:file_fusion}
security:
  secret:
    key: ${FF_SECRET_KEY:fDdXuRJmui73NjU9}
    iv: ${FF_SECRET_IV:t7M1BjL1wLKE6hyc}
task:
  clear-thumbnail-file: ${FF_TASK_CLEAR_THUMBNAIL_FILE:0 0 1 * * ?}
file:
  dir: ${FF_FILE_DIR:/opt/file_fusion/data/file}
  lock-timeout: ${FF_TIMEOUT:60s}
  download-link-timeout: ${FF_TIMEOUT:60s}
thumbnail:
  dir: ${FF_THUMBNAIL_DIR:/opt/file_fusion/data/thumbnail}
  generate-timeout: ${FF_TIMEOUT:60s}
  image-mime-type: "${FF_THUMBNAIL_IMAGE_MIME_TYPE:application/pdf,\
  application/postscript,\
  image/bmp,\
  image/gif,\
  image/heic,\
  image/jpeg,\
  image/png,\
  image/sgi,\
  image/svg+xml,\
  image/tiff,\
  image/vnd.adobe.photoshop,\
  image/webp,\
  image/x-xbitmap}"
  video-mime-type: "${FF_THUMBNAIL_VIDEO_MIME_TYPE:application/vnd.rn-realmedia,\
  video/x-ms-wmv,\
  video/mp4,\
  video/mpeg,\
  video/3gpp,\
  video/x-flv,\
  video/quicktime,\
  video/mp4,\
  video/x-flv,\
  video/webm,\
  video/avi}"
